### ISSUE TITLE
Any chances for writing a blog for GBDT?

### ISSUE THREAD

**Issue by hdjsjyl** [EricWebsmith/machine_learning_from_scrach#2]
As the subject, thanks for your work.

**Comment by EricWebsmith** [comment]
Thanks for your trust. I have written two posts about GBDT:

https://ericwebsmith.github.io/2020/04/12/GradientBoostingRegression/
https://ericwebsmith.github.io/2020/04/19/GradientBoostingClassification/

You can also find them in this repo.
